<script>
    require([
        "zipMoneyWidgetJs"
    ]);
    // merchant Id
    zip_widget_merchantId = '<?php  echo $this->getMerchantPublicKey();?>';
    // Environment like sandbox or production
    zip_widget_env = '<?php  echo $this->getEnvironment();?>';
    // region like au/nz/uk/us/za
    zip_widget_region = '<?php  echo strtolower($this->getRegion());?>';
    // max price to show the zip cart or product widget
    zip_widget_max_price = '<?php  echo $this->getOrderTotalMaximum();?>';
    // min price to show the zip cart or product widget
    zip_widget_min_price = '<?php  echo $this->getOrderTotalMinimum();?>';
    // widget display inline if this value is true otherwise it will display iframe
    zip_widget_display_inline = '<?php  echo $this->isDisplayInlineWidget();?>';
    // product price for dynamic widget
    <?php
    if ($this->getPageType() == 'cart') :?>
        zip_widget_cart_price = <?php echo $this->getCartTotal();?>;
    <?php endif;?>
    <?php if ($this->getPageType() == 'product') :?>
        zip_widget_product_price = <?php echo $this->getProductPrice();?>;
    <?php endif; ?>
    // display widget selector
    <?php foreach ($this->getElementSelectors() as $key => $selector): ?>
    zip_widget_<?php echo $this->escapeHtml($key); ?>="<?php echo $this->escapeHtml($selector); ?>";
    <?php endforeach; ?>
</script>
