<div class="zip-  -message">                    
    <img style="float: right; padding-right: 17px; padding-top: 5px;  width: 150px;"/>
    <p><strong><?php echo $this->getErrorTypeText();?></strong> <?php echo $this->getBodyText(); ?></p>
</div>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo  __('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'">
        <span><span><?php echo __('Continue Shopping') ?></span></span>
    </button>
</div>
